engines:
  csslint:
    enabled: true
    exclude_fingerprints:
    - 61f883d4595213cf22a4027e8fa0686b #ignore 0px for margin-bottom on h tags
    - 61f883d4595213cf22a4027e8fa0686b #ignore 0px for padding 0px (responsive)
    checks:
      shorthand:
        enabled: false
      fallback-colors:
        enabled: false
      box-sizing:
        enabled: false #who cares about compatibility with IE 6/7?
  fixme:
    enabled: true
    exclude_fingerprints:
    - c19c0332e1b825dd4f9222d5bc21f0a9 #todo in assets/favicon/rfg_request.json
    - 84c8539ac58fe954b23b6f3b2d53a4ac #assets/favicon/rfg_request_notinline.json
  phpcodesniffer:
    enabled: true
    checks:
      Generic WhiteSpace DisallowTabIndent TabsUsed:
        enabled: false
      Squiz WhiteSpace ScopeClosingBrace ContentBefore:
        enabled: false
      ControlStructures ControlSignature SpaceAfterKeyword:
        enabled: false
  phpmd:
    enabled: true
    checks:
      Controversial/Superglobals:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
ratings:
  paths:
  - "**.php"
  - "**.module"
  - "**.inc"
  - "**.css"
